"""Vendor the site's existing Google Fonts with their upstream OFL licenses.

Requires only Python's standard library. The Xuanye fonts use Google's text
subset API, covering every character in both versions of that page plus ASCII.
Run again after adding new characters to Xuanye's copy.
"""

from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
import hashlib
import json
import re
from urllib.parse import quote, urlparse
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "public/fonts"
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"


def download(url):
    with urlopen(Request(url, headers={"User-Agent": USER_AGENT}), timeout=90) as response:
        return response.read()


def vendor_css(name, query):
    url = "https://fonts.googleapis.com/css2?" + query + "&display=swap"
    css = download(url).decode("utf-8")
    urls = sorted(set(re.findall(r"url\((https://[^)]+)\)", css)))
    targets = {}

    def vendor_font(font_url):
        assert urlparse(font_url).hostname == "fonts.gstatic.com"
        data = download(font_url)
        assert data[:4] == b"wOF2", "Expected browser-ready WOFF2"
        filename = f"{name}-{hashlib.sha256(data).hexdigest()[:12]}.woff2"
        (FONT_DIR / filename).write_bytes(data)
        return font_url, filename

    with ThreadPoolExecutor(max_workers=6) as pool:
        for original, filename in pool.map(vendor_font, urls):
            targets[original] = filename
            css = css.replace(original, f"/fonts/{filename}")
    (FONT_DIR / f"{name}.css").write_text(
        "/* Generated by scripts/localize_google_fonts.py. Licensed under SIL OFL. */\n" + css,
        encoding="utf-8",
    )
    unique = sorted(set(targets.values()))
    print(f"{name}: {len(unique)} fonts, {sum((FONT_DIR / file).stat().st_size for file in unique):,} bytes")
    return {"stylesheet_source": url, "files": unique}


def main():
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    main_fonts = vendor_css("portfolio", "family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400;1,600&family=Caveat:wght@600;700")
    sources = [ROOT / "src/components/Xuanye.tsx", ROOT / "public/xuanye.html"]
    text = "".join(path.read_text(encoding="utf-8") for path in sources)
    characters = "".join(sorted({char for char in text if not char.isspace()} | set(map(chr, range(32, 127)))))
    xuanye_fonts = vendor_css(
        "xuanye",
        "family=Noto+Serif+SC:wght@300..900&family=Cormorant+Garamond:ital,wght@0,300..600;1,400&family=Ma+Shan+Zheng&text=" + quote(characters, safe=""),
    )
    license_dir = FONT_DIR / "licenses"
    license_dir.mkdir(exist_ok=True)
    for family in ["caveat", "playfairdisplay", "notoserifsc", "cormorantgaramond", "mashanzheng"]:
        url = f"https://raw.githubusercontent.com/google/fonts/main/ofl/{family}/OFL.txt"
        license_text = download(url)
        assert b"SIL OPEN FONT LICENSE" in license_text
        (license_dir / f"{family}-OFL.txt").write_bytes(license_text)
    (FONT_DIR / "sources.json").write_text(json.dumps({
        "portfolio": main_fonts,
        "xuanye": {**xuanye_fonts, "subset_characters": characters},
        "license_repository": "https://github.com/google/fonts/tree/main/ofl",
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Xuanye subset covers {len(characters)} source characters; unsupported symbols retain the existing serif fallback.")


if __name__ == "__main__":
    main()
